### ISSUE TITLE
Downloading the courses are really slow

### ISSUE THREAD

**Issue by naithagoni** [r0oth3x49/acloud-dl#107]
I was especially downloading **AWS Certified Developer - Associate (DVA-C02)**, the downloading was really fast for a few courses for instance 1 - 3 out of 13, then, the downloading process is down from course 3 and taking really long time to finish the download.

**Comment by r0oth3x49** [comment]
@naithagoni the tool has nothing to do with download speed because I am not able to reproduce such issue or never faced this before , did you tried downloading on some sort of vps to check if actually the tools is causing this problem
