### ISSUE TITLE
I

### ISSUE THREAD

**Issue by TrueCitrus** [r0oth3x49/acloud-dl#11]
I have tried all the steps in the readme to export the request headers from Firefox and save to a cookies.txt file however I keep getting this error:
[-] : Authorization error : it seems your authorization token is expired.
[i] : Login again & copy Request headers for a single request to file..

I have tried exporting the request headers from learn.acloud.guru which then spits out the error message immediately. If I try the request headers from split.io the script seems to pause for a bit and then eventually spits out the same error.

Am I doing something wrong?

**Comment by yassinelazaar** [comment]
I second this

**Comment by 01ttouch** [comment]
![firefox-logo](https://user-images.githubusercontent.com/50474221/58747649-af563c00-845d-11e9-87ea-e5297c47f2b8.png) Simple 5 steps login with cookie for <b>Firefox</b> users

1) Make sure you already <b>logged in</b> and <b>make sure you visit</b>: https://learn.acloud.guru . Right click anywhere on the acloud website and choose <b>Inspect Element</b> or you can press shortcut button <b>F12</b>

![firefox1](https://user-images.githubusercontent.com/50474221/58747662-d6147280-845d-11e9-8319-44f65268987a.png)

2) Choose <b>Storage</b> tab, then choose <b>Cookies</b> -> `https://learn.acloud.guru` on the left.

On the right, type into filter: <b>auth0_token</b>, double click and copy the value inside <b>Value</b> box.

![firefox2](https://user-images.githubusercontent.com/50474221/58747664-e3316180-845d-11e9-8c73-99449a06f38c.png)

3) Create a text (<b>.txt</b>) file inside your <b>acloud-dl</b> folder, name it whatever you want.

![firefox3](https://user-images.githubusercontent.com/50474221/58747669-ed536000-845d-11e9-99b5-5b10c1b2bf2c.png)

4) Open the text (<b>.txt</b>) file you just created. Add the line below to it, replace <b>yourAuthToken</b> with the value in <b>Step 2</b> and save the file.

`auth0_token=yourAuthToken`

![firefox4](https://user-images.githubusercontent.com/50474221/58747673-f6dcc800-845d-11e9-867d-7ad002ce3103.png)

5) Use the command below to login and download with cookie. Replace <b>cookie.txt</b> with the name of file you created in <b>Step 3</b>

`python acloud-dl.py -c cookie.txt`

![firefox5](https://user-images.githubusercontent.com/50474221/58747674-fe9c6c80-845d-11e9-9648-13bd658b5d2c.png)

**Comment by 01ttouch** [comment]
![chrome-logo](https://user-images.githubusercontent.com/50474221/58747758-188a7f00-845f-11e9-91cc-741a46ca75ce.png) Simple 5 steps login with cookie for <b>Chrome</b> users

1) Make sure you already <b>logged in</b> and <b>make sure you visit</b>: https://learn.acloud.guru . Right click anywhere on the acloud website and choose <b>Inspect</b> or you can press shortcut button <b>F12</b>

![chrome1](https://user-images.githubusercontent.com/50474221/58747762-26d89b00-845f-11e9-8fd3-ace65d71cb89.png)

2) Choose <b>Application</b> tab, then choose <b>Cookies</b> -> `https://learn.acloud.guru` on the left.

On the right, type into filter: <b>auth0_token</b>, double click and copy the value inside <b>Value</b> box.

![chrome2](https://user-images.githubusercontent.com/50474221/58747765-2d671280-845f-11e9-95c7-04bae506544f.png)

3) Create a text (<b>.txt</b>) file inside your <b>acloud-dl</b> folder, name it whatever you want.

![chrome3](https://user-images.githubusercontent.com/50474221/58747770-3ce65b80-845f-11e9-83ee-14ba1f993d99.png)

4) Open the text (<b>.txt</b>) file you just created. Add the line below to it, replace <b>yourAuthToken</b> with the value in <b>Step 2</b> and save the file.

`auth0_token=yourAuthToken`

![chrome4](https://user-images.githubusercontent.com/50474221/58747776-47a0f080-845f-11e9-8c49-12599a230ade.png)

5) Use the command below to login and download with cookie. Replace <b>cookie.txt</b> with the name of file you created in <b>Step 3</b>

`python acloud-dl.py -c cookie.txt`

![chrome5](https://user-images.githubusercontent.com/50474221/58747781-5687a300-845f-11e9-8135-f9b115cc5244.png)

**Comment by 01ttouch** [comment]
You guys need to wait the author @r0oth3x49 merge the pull request i made before you can follow the guide above

Or you can download my fork and follow the guide above : https://github.com/01ttouch/acloud-dl/archive/login-problem-with-cookie.zip

**Comment by r0oth3x49** [comment]
> 
> 
> I have tried all the steps in the readme to export the request headers from Firefox and save to a cookies.txt file however I keep getting this error:
> [-] : Authorization error : it seems your authorization token is expired.
> [i] : Login again & copy Request headers for a single request to file..
> 
> I have tried exporting the request headers from learn.acloud.guru which then spits out the error message immediately. If I try the request headers from split.io the script seems to pause for a bit and then eventually spits out the same error.
> 
> Am I doing something wrong?


Steps
 - Right click any where once you are logged in to your account.
 - Click on **Inspect Element** 
 - Then Click on **Network Tab**
- Click on **Courses** in the Menu Bar
 - Check a successfull POST request going to `https://prod-api.acloud.guru/bff/graphql/protected`
 - Right click and copy the requests Headers.
- Done

**Comment by rasikbapotra** [comment]
I'm not able to see any details:
![image](https://user-images.githubusercontent.com/20127361/87842546-d45c7700-c8ca-11ea-973f-7a0bb61144af.png)

**Comment by rasikbapotra** [comment]
Now getting below error:
![image](https://user-images.githubusercontent.com/20127361/87848340-ed7e1b80-c8fc-11ea-9f8b-253ebed92ac6.png)

**Comment by rasikbapotra** [comment]
Its working now. Thanks for your help.
