### ISSUE TITLE
user input is required,no input specified

### ISSUE THREAD

**Issue by ayush14rastogi** [r0oth3x49/acloud-dl#15]
hi i am getting below issue can anybody help here
![Capture](https://user-images.githubusercontent.com/31894500/59842672-a1b51780-9374-11e9-89c1-de3db1fbc491.JPG)

**Comment by r0oth3x49** [comment]
where are the courses? you should at least 1st start the course and then run this to download, nothing showing there what kind of input it should accept. i will check that. try that once it list down courses and let me know if you still face that error

**Comment by mpostument** [comment]
Have the same issue

**Comment by r0oth3x49** [comment]
@mpostument can you see courses list down in  the output ? before the choices?

**Comment by mpostument** [comment]
@r0oth3x49 at first I tried to use on account with a trial subscription. And there was the same situation as in @ayush14rastogi . But once I take account with the full subscription I was able to download courses

**Comment by r0oth3x49** [comment]
> 
> 
> @r0oth3x49 at first I tried to use on account with a trial subscription. And there was the same situation as in @ayush14rastogi . But once I take account with the full subscription I was able to download courses

so basically the problem is solved for you right?

**Comment by mpostument** [comment]
Yep

**Comment by rasikbapotra** [comment]
I'm not getting anything when running command
![image](https://user-images.githubusercontent.com/20127361/87842415-f86b8880-c8c9-11ea-9a3b-a8b1a2a00ae8.png)
[](url)

**Comment by rasikbapotra** [comment]
Its working now.
