### ISSUE TITLE
Video Quality Flag may be incorrect

### ISSUE THREAD

**Issue by mindovermiles262** [r0oth3x49/acloud-dl#18]
I'm seeing something strange when trying to download the smallest-sized video files. I would suspect that the same video in 480p would be a fraction of the size of the same video in 720, but according to the program, using the `-i` flag, the 720p video is smaller in size:

```
[*] : Lecture(s) (2).
     - duration   : 01:57.
     - Lecture id : [REDACTED]
        - video:mp4@1920x1080     1080p   12.07MB (Best)
        - video:mp4@854x480       480p    18.45MB 
        - video:mp4@1280x720      720p    10.49MB 
        - file:pdf@pdf            pdf     551.46KB
```

Is this true? Is there any way to verify this?

**Comment by r0oth3x49** [comment]
seems strange, but i don't have any account yet, i might your account to reproduce and check what's going on.
