### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement acloud (from versions: none)

### ISSUE THREAD

**Issue by theend822** [r0oth3x49/acloud-dl#19]
requirement.txt executed. 
cURL copied in a file aaa.txt
![1](https://user-images.githubusercontent.com/55083781/64518209-54699600-d324-11e9-8218-628889127bf4.png)

when try to run python acloud-dl.py -c aaa.txt
shows error "ModuleNotFoundError: No module named 'acloud'"

try to pip install acloud
shows error "ERROR: Could not find a version that satisfies the requirement acloud (from versions: none)
ERROR: No matching distribution found for acloud"
![Annotation](https://user-images.githubusercontent.com/55083781/64518360-97c40480-d324-11e9-859c-925c65b365ac.png)

**Comment by r0oth3x49** [comment]
@theend822 this cannot be installed using pypi, you should download it from here and use.
