### ISSUE TITLE
Getting Token Expired Error

### ISSUE THREAD

**Issue by amsheenbs** [r0oth3x49/acloud-dl#21]
I'm currently trying to use the tool and am continuously getting this error.

**[-] : Authorization error : it seems your authorization token is expired.
[i] : Login again & copy Request headers for a single request to file..**

This is the content of my cookie file:
`curl 'https://prod-api.acloud.guru/bff/graphql' -H 'Sec-Fetch-Mode: cors' -H 'Origin: https://learn.acloud.guru' -H 'authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJAUTHCODEAUTHCODEeJRoYzLqm2OrQ' -H 'content-type: application/json' -H 'accept: */*' -H 'Referer: https://learn.acloud.guru/browse' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36' -H 'apollographql-client-version: 633' -H 'apollographql-client-name: learn-production' --data-binary '{"operationName":"handsonLabs","variables":{},"query":"query handsonLabs {\n  handsonLabs {\n    labs {\n      labId\n      title\n      labUrl\n      thumbnailUrl\n      duration\n      isPopular\n      topic\n      vendor\n      service\n      technology\n      difficulty\n      createdDate\n      updatedDate\n      publishedDate\n      __typename\n    }\n    __typename\n  }\n}\n"}' --compressed`

**Comment by r0oth3x49** [comment]
@amsheenbs when you are logged in to your account the cookies works fine but when you logged out the cookies gets expired which i think the case is here.

don't log out from your account in browser and it should work fine, if not then your credentials would be required to reproduce and fix the issue.

if you are okay with sharing creds you can email me on `nasir251292@gmail.com`.
