### ISSUE TITLE
Getting error UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1418: character maps to <undefined>

### ISSUE THREAD

**Issue by manjshet** [r0oth3x49/acloud-dl#24]
getting error when trying to download from acloud guru.

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1418: character maps to <undefined>

[acloud_cookie.txt](https://github.com/r0oth3x49/acloud-dl/files/4178187/acloud_cookie.txt)

**Comment by r0oth3x49** [comment]
you can send the cookies of account creds on email on this weekend to my email so that i can check and fix. email --> `nasir251292@gmail.com`
