### ISSUE TITLE
Is this still functional?

### ISSUE THREAD

**Issue by stevegreen22** [r0oth3x49/acloud-dl#25]
Hi, 
I'm trying to use so I can download and watch offline but either they've charged their architecture or I'm not able to see the requests - can anyone confirm if this is still functional please?

**Comment by r0oth3x49** [comment]
Hey @stevegreen22, it should be if not working for you then at the time i don't have any credentials to check and fix, would be great if you can share your creds on email `nasir251292@gmail.com`.
