### ISSUE TITLE
OSError: [Errno 22] Invalid argument:

### ISSUE THREAD

**Issue by harryrbob** [r0oth3x49/acloud-dl#28]
when the filename has got characters like '(', ')' it fails, error looks like below couple of examples below:

_Traceback (most recent call last):
  File "acloud-dl.py", line 322, in <module>
    main()
  File "acloud-dl.py", line 315, in main
    acloud.course_download(path=options.output, quality=options.quality, download_all=options.download_all)
  File "acloud-dl.py", line 231, in course_download
    self.download_lectures_only(lecture_best=lecture_best, lecture_title=lecture_title, inner_index=lecture_index, lectures_count=lectures_count, lecture_assets=lecture_assets, lecture_subs=lecture_subs, filepath=filepath)
  File "acloud-dl.py", line 169, in download_lectures_only
    self.download_assets(lecture_assets=lecture_assets, filepath=filepath)
  File "acloud-dl.py", line 128, in download_assets
    assets.download(filepath=filepath, quiet=True, callback=self.show_progress)
  File "E:\XXXX\acloud-dl\acloud\_shared.py", line 765, in download
    return self._write_external_links(filepath)
  File "E:\XXXX\acloud-dl\acloud\_shared.py", line 695, in _write_external_links
    with open('{}'.format(filename), 'a', encoding='utf-8') as f:
OSError: [Errno 22] Invalid argument: 'E:/XXXYYYZZZ/\\Google Kubernetes Engine (GKE): Beginner to Pro\\01 Intro to Containers'_
======
eg: 2
======
Downloading (001 Course introduction and information)
[*] : Lecture : '001 Course introduction and information' (download skipped).
[-] : Reason : [Errno 22] Invalid argument: 'E:/XXXYYYZZZ/\\LPIC-1: System Administrator\\01 Introduction.part'

OSError: [Errno 22] Invalid argument: 'E:/XXXYYYZZZ/\\LPIC-1: System Administrator\\04 Exam 1 (102) - Linux installation and package management'

**Comment by amitfegade121** [comment]
This error occurred because of character ":" (colon). Winows doesn't allow this charatcer in folder name. I am facing the same problem. We have to replace this : with blank space.
