### ISSUE TITLE
Request : can you show how should the cookies file look like  a screenshot will be of great help

### ISSUE THREAD

**Issue by ArjunDandagi** [r0oth3x49/acloud-dl#3]

**Comment by r0oth3x49** [comment]
by cookies i mean the request headers. with firefox you can copy request headers (`Copy Request Headers`) while with chrome you can copy the entire request as curl (`Copy Request as cURL`).

The below Request headers are the example from Firefox.
```
POST /bff/graphql/protected HTTP/1.1
Host: prod-api.acloud.guru
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:63.0) Gecko/20100101 Firefox/63.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://acloud.guru/
Authorization: Bearer {ACCESS_TOKEN}
Content-Type: application/json;charset=utf-8
Content-Length: 673
Origin: https://acloud.guru
DNT: 1
Connection: keep-alive
```

**Comment by kassmuteit** [comment]
Sorry, but it does not work for me. What is the name / path of the XHR ( public / private )? How does ist work on Windows and IE ? How does it work on OS X and Safari ?
Sorry, but there are a lot of entries and no one looks like the example. May be I am to blind to find that.

cheers,
karl
