### ISSUE TITLE
Syntax error from windows

### ISSUE THREAD

**Issue by neoluu** [r0oth3x49/acloud-dl#30]
Hi,

Running from windows 10 and haved installed requirements. Get the following when trying to execute.

PS C:\temp\acloud-dl-master> python acloud-dl.py -c cookie.txt
Traceback (most recent call last):
  File "acloud-dl.py", line 7, in <module>
    import acloud
  File "C:\temp\acloud-dl-master\acloud\__init__.py", line 32, in <module>
    from ._acloud import courses
  File "C:\temp\acloud-dl-master\acloud\_acloud.py", line 26, in <module>
    from ._internal import InternCloudGuruCourses as CloudGuru
  File "C:\temp\acloud-dl-master\acloud\_internal.py", line 30, in <module>
    from ._extract import CloudGuru
  File "C:\temp\acloud-dl-master\acloud\_extract.py", line 297
    subtitle_url = f"https://acloudguru-subtitles-production.s3.amazonaws.com/{cid.group()
}.vtt"

     ^
SyntaxError: invalid syntax

Thanks

**Comment by hcheruku** [comment]
Remove that f in subtitle url. Change it to:
```
subtitle_url = "https://acloudguru-subtitles-production.s3.amazonaws.com/{cid.group()
}.vtt"
```

worked for me :-)
There are other errors I got and I fixed them too. Let me know if you see any.

**Comment by neoluu** [comment]
Thanks. that worked.

Do you know how to can avoid this?  want to let it run overnight? 

[*] : Course 'AWS Certified Developer - Associate 2017'.
[-] : Authorization error : it seems your authorization token is expired.
[i] : Login again & copy Request headers for a single request to file..

**Comment by neoluu** [comment]
Figured out the issue. I will open a new issue for tracking purpose. Thanks again

**Comment by yecine06** [comment]
I have the same issue

how did you solve it ?
