### ISSUE TITLE
Authorization error : it seems your authorization token is expired.

### ISSUE THREAD

**Issue by neoluu** [r0oth3x49/acloud-dl#31]
Hi,

I believe the below error is a false positive.

All videos downloaded, looks like that error is triggered when it tries to download the Quiz, which isn't a video.

[*] : Course 'AWS Certified Developer - Associate 2017'.
[-] : Authorization error : it seems your authorization token is expired.
[i] : Login again & copy Request headers for a single request to file..

Thanks

**Comment by hcheruku** [comment]
I think you can't avoid that error coz the CID expires and the headers change every few hours.
I gave/changed the headers 3 times in the entire download process.

Also, when the download is happening - don't touch the browser. I think that's also refreshing the headers. Not sure.

I modified the script a little:
- to get the new headers for every 7 courses and supplied it to the script.
- added `encode('ascii', 'ignore')` for few lines coz some of the courses have those ascii values.
- added another argparse argument to just download selected multiple courses. (the script has one at a time OR all)

Good Luck!

**Comment by neoluu** [comment]
just an FYI, when I get this error I do not need to re-login to site to continue to download other courses.

Anyhow awesome tool!
