### ISSUE TITLE
 Zero accessable courses

### ISSUE THREAD

**Issue by yecine06** [r0oth3x49/acloud-dl#33]
Hello,

When i launch the command it can't find any course, my cookie has been copied from chrome

python acloud-dl.py -c cookie.txt

              __                __          ____
  ____ ______/ /___  __  ______/ /     ____/ / /
 / __ `/ ___/ / __ \/ / / / __  /_____/ __  / /
/ /_/ / /__/ / /_/ / /_/ / /_/ /_____/ /_/ / /
\__,_/\___/_/\____/\__,_/\__,_/      \__,_/_/

                                 Version : 0.1
                                 Author  : Nasir Khan (r0ot h3x49)
                                 Github  : https://github.com/r0oth3x49

[-] : Zero accessable courses: no courses found in your accessable courses.
[i] : Click 'START THIS COURSE' button to be able to get listed for download..
[i] : OR follow --> (https://github.com/r0oth3x49/acloud-dl#usage) for proper help..

**Comment by r0oth3x49** [comment]
This is not an issue you see the guide line provided with the link
