### ISSUE TITLE
Long filenames (and presumably paths) are an issue in Windows

### ISSUE THREAD

**Issue by jonohein** [r0oth3x49/acloud-dl#34]
I have a fix but you might want to implement your own.
https://github.com/jonohein/acloud-dl/commit/4170082c88bd80b2301a6ba9d097ff82a8bb4613

For and issue file, see 'AWS Certified Advanced Networking - Specialty 2020\03 Configure Network Integration with Application Services\013 Maintaining Transport Layer Security All the Way to Your Container Using the Network Load Balanc....txt'

It gives a file not found error when using 'with open' in _shared.py

**Comment by jonohein** [comment]
I've put a PR for my fix: https://github.com/r0oth3x49/acloud-dl/pull/35

**Comment by r0oth3x49** [comment]
@jonohein thanks for the PR but adding only these two lines would have done the work i guess.

```python
if os.name == "nt" and len(filepath) > 250:
    filepath = "\\\\?\\{}".format(filepath)
```

**Comment by r0oth3x49** [comment]
@jonohein nice one to use the range import, thanks for that.
