### ISSUE TITLE
Issue downloading last chapter of specific course.

### ISSUE THREAD

**Issue by mjmaruf** [r0oth3x49/acloud-dl#39]
Course Link: https://learn.acloud.guru/course/gke-beginner-to-pro/dashboard

The beginning of the course downloads fine except this chapter. Seems like an encoding issue. 

![Screen Shot 2020-06-20 at 4 52 58 PM](https://user-images.githubusercontent.com/67207002/85211455-664a8180-b317-11ea-89a5-baca5979a46e.png)

**Comment by jassics** [comment]
Same here. Not just the last course, possible all the latest courses.

**Comment by mjmaruf** [comment]
Thanks Nasir!
