### ISSUE TITLE
object is not iterable

### ISSUE THREAD

**Issue by summerrain1234** [r0oth3x49/acloud-dl#43]
Thanks but it didnt download the mp4s only the headings using python acloud-dl.py -c cookies.txt -q 1080

**Comment by r0oth3x49** [comment]
@summerrain1234 are you using latest one?

**Comment by summerrain1234** [comment]
r0oth3x49 only the title and chapter headings are downloaded not the mp4s

**Comment by r0oth3x49** [comment]
this issue seems similar, but i can't reproduce the issue as i don't have a pro account, would be great if you can share on `nasir251292@gmail.com` otherwise i don't have any choice to track and fix the issue.

**Comment by rakeshkanagaraj1990** [comment]
@r0oth3x49 Same here. I have emailed you the credentials. Free trial to end soon :| 
Course Name: Mastering AWS CloudFormation
Thanks for your good work. It would be nice if you can find a fix sooner.

**Comment by r0oth3x49** [comment]
will push the fix soon. 
thanks @rakeshkanagaraj1990 for sharing.
