### ISSUE TITLE
Not able to download SRT files, attachments & AWS CSAA, CSAP courses

### ISSUE THREAD

**Issue by rakeshkanagaraj1990** [r0oth3x49/acloud-dl#46]
After the latest patches, it is not downloading subtitles and attachments. 

and Download courses by providing range to start from
if I select 1 its downloads all the available courses, rest of the course selection numbers are working fine

**Comment by r0oth3x49** [comment]
the srt one i removed, i will implement that properly later on.

you mean if you provide range option as 1+ it downloads all? (if yes then it is intended behavior you are providing a starting point to the tool to start from 1 and download all the courses after that), if i'm not getting you properly then explain a bit more

**Comment by rakeshkanagaraj1990** [comment]
@r0oth3x49 

Issue 1) I wanted to download only [1] - Automating AWS with python

[*] : Downloading accessible courses information .. (done)
[1] : Automating AWS with Python
[2] : Advanced AWS CloudFormation
[3] : AWS Certified Developer - Associate 2020
[4] : AWS Certified Big Data - Specialty 2019
[?] : provide range (e.g:- 3+) or select course number between (1/24/all/range): 1

If I provide 1 - it is downloading the Automating AWS with Python, once completed it is continuing to download the other courses too in the sequential order 2,3,4 etc., ( input variable of 1 is getting considered as 1+)

I am not giving 1+ it is just 1 which needs to download only Automating AWS with Python once done need to exit. 

Issue 2) Couldn't download following courses getting below errors 

AWS Certified Solutions Architect Associate 2020
AWS Certified Solutions Architect - Professional 2020

I have a good internet connection able to download other courses


[*] : Downloading chapter : (1 of 13)
[+] : Chapter (01 Introduction)
[*] : Found (3) lectures ...

[*] : Lecture(s) : (1 of 3)
[*] : Downloading (001 Introduction)
[*] : 23.79MB/23.79MB 100.00% |##############################| 839.51kB/s
[+] : Downloaded  (001 Introduction)

[*] : Lecture(s) : (2 of 3)
[*] : Downloading (002 The Exam Blueprint)
[*] : Lecture : '002 The Exam Blueprint' (download skipped).
**[-] : URLError : either your internet connection is not working or server aborted the request**

[*] : Lecture(s) : (3 of 3)
[*] : Downloading (003 Why Should I Learn and Get Certified with AWS)
[*] : Lecture : '003 Why Should I Learn and Get Certified with AWS' (download skipped).
[-] : URLError : either your internet connection is not working or server aborted the request

[*] : Downloading chapter : (2 of 13)
[+] : Chapter (02 AWS - 10000-Foot Overview)
[*] : Found (4) lectures ...

**Comment by rakeshkanagaraj1990** [comment]
@r0oth3x49 credentials to be expired by 9 PM IST tomorrow.
