### ISSUE TITLE
Issue in downloading new contents

### ISSUE THREAD

**Issue by jassics** [r0oth3x49/acloud-dl#48]
I tried to download AWS CCP and AWS SAA-C02 and in most of the cases it is showing "[-] : URLError : either your internet connection is not working or server aborted the request"

But for others its working fine.

**Comment by sh1dow3r** [comment]
I'm facing the same issue as well.. 

More output here if needed:
 `[*] : Lecture(s) : (1 of 4)
[*] : Downloading (001 Good Luck)
[*] : Lecture : '001 Good Luck' (download skipped).
[-] : URLError : either your internet connection is not working or server aborted the request

[*] : Lecture(s) : (2 of 4)
[*] : Downloading (002 Stay Engaged)
[*] : Lecture : '002 Stay Engaged' (download skipped).
[-] : URLError : either your internet connection is not working or server aborted the request

[*] : Lecture(s) : (3 of 4)
[*] : Downloading (003 Keep Going)
[*] : Lecture : '003 Keep Going' (download skipped).
[-] : URLError : either your internet connection is not working or server aborted the request`

**Comment by r0oth3x49** [comment]
@jassics already reported #47 , will work on this need to check if credential works or not.

**Comment by moonj86** [comment]
Got the same error, was able to download another course, but not this one and anather one.
[-] : URLError : either your internet connection is not working or server aborted the request

**Comment by tonisc** [comment]
Hi,
I have the same issue. I can't download AWS-Solutions Architect Professional. Only the first video (Introduction - 1m downs fine).
Is possible to solve this?
