### ISSUE TITLE
UnboundLocalError: local variable 'height' referenced before assignment

### ISSUE THREAD

**Issue by sohahm** [r0oth3x49/acloud-dl#52]
I am getting the following error while downloading 

Python 3 Scripting for System Administrators
and 
Introduction to Ansible

> [*] : Course 'Introduction to Ansible'.
> Traceback (most recent call last):on ..
>   File "acloud-dl.py", line 334, in <module>
>     main()
>   File "acloud-dl.py", line 327, in main
>     acloud.course_download(path=options.output, quality=options.quality, download_all=options.download_all)
>   File "acloud-dl.py", line 209, in course_download
>     course = course.get_course(keep_alive=download_all)
>   File "C:\Code\acloud-dl\acloud\_shared.py", line 88, in get_course
>     self._process_course(keep_alive=keep_alive)
>   File "C:\Code\acloud-dl\acloud\_internal.py", line 69, in _process_course
>     self._course = InternCloudGuruCourse(self._info, self._session, keep_alive)
>   File "C:\Code\acloud-dl\acloud\_internal.py", line 79, in __init__
>     super(InternCloudGuruCourse, self).__init__()
>   File "C:\Code\acloud-dl\acloud\_shared.py", line 109, in __init__
>     self._fetch_course()
>   File "C:\Code\acloud-dl\acloud\_internal.py", line 85, in _fetch_course
>     self._info              =       self._real_extract(course_id=course_id)
>   File "C:\Code\acloud-dl\acloud\_extract.py", line 486, in _real_extract
>     'lectures' : self._extract_lectures(lectures)
>   File "C:\Code\acloud-dl\acloud\_extract.py", line 405, in _extract_lectures
>     sources = self._extract_sources(sources)
>   File "C:\Code\acloud-dl\acloud\_extract.py", line 246, in _extract_sources
>     'height' : height,
> UnboundLocalError: local variable 'height' referenced before assignment

**Comment by r0oth3x49** [comment]
@sohahm already reported #50
