### ISSUE TITLE
how to copy header and save to txt  

### ISSUE THREAD

**Issue by devopsdymyr** [r0oth3x49/acloud-dl#6]
![Screenshot from 2019-04-03 10-00-10](https://user-images.githubusercontent.com/41105507/55452924-5bfb7500-55f7-11e9-9328-00ac16a88d61.png)

**Comment by r0oth3x49** [comment]
@devopsdymyr you can follow any video / tut over internet. i have also written i criteria in README.md

**Comment by digineo1** [comment]
I get the same error. I've saved the request headers to a text file but it's still not being recognized. Are you looking for the full headers or just the cookie?

**Comment by devopsdymyr** [comment]
Not clear, still confused on download header

**Comment by nicosto** [comment]
hi, any link to some tuto/video will be really appreciated.

**Comment by r0oth3x49** [comment]
@nicosto [here you go, it is for udemy-dl but the process is same](https://github.com/r0oth3x49/udemy-dl/issues/303#issuecomment-441345792)
