### ISSUE TITLE
AttributeError: 'HTMLParser' object has no attribute 'unescape'

### ISSUE THREAD

**Issue by SanthoshNaveen1986** [r0oth3x49/acloud-dl#61]
Hi Nasir,

Getting this error "AttributeError: 'HTMLParser' object has no attribute 'unescape'" while downloading the 'AWS Certified Developer - Associate 2020' course.
First chapter gets downloaded and then the error comes.

![image](https://user-images.githubusercontent.com/72742324/95744311-b9728680-0cb0-11eb-964f-14d4678a24d7.png)

**Comment by SanthoshNaveen1986** [comment]
I am using Python 3.9

**Comment by SanthoshNaveen1986** [comment]
I have not installed python version 3.8* and it works fine. But I can see only few courses which can be downloaded. Any restriction?

**Comment by tirkarthi** [comment]
This is due to https://bugs.python.org/issue37328 .

**Comment by SanthoshNaveen1986** [comment]
> This is due to https://bugs.python.org/issue37328 .

Thanks Karthikeyan Singaravelan. The issue was resolved once i downgraded to ver 3.8

**Comment by SanthoshNaveen1986** [comment]
I was able to download more courses after i added them into my dashboard in acloudguru. 
Thanks Nasir for the amazing tool
