### ISSUE TITLE
URLError : either your internet connection is not working or server aborted the request

### ISSUE THREAD

**Issue by DConcellon** [r0oth3x49/acloud-dl#64]
Hi,

I'm using the latest version, but when I'm trying to download my AWS Solutions Architect Associate, it gives me this error.

Can you help me? What can I do?

Thanks in advice

**Comment by r0oth3x49** [comment]
@DConcellon i might need an account to reproduce and fix the issue, if you are okay sharing account or cookie file would be great otherwise i can't check what causing the issue.

in case you are okay to share creds or cookie file you can email it to: `nasir251292@gmail.com`.

**Comment by arun25463** [comment]
same issue from myside as well. Only few videos download where as the other videos give the error as below
" URLError : either your internet connection is not working or server aborted the request"
Please fix this issue.
Thank you

**Comment by yashwanth099** [comment]
same problem for me also

**Comment by myturf** [comment]
First , thank you for awesome utility , Sent my cookies file to nasir251292@gmail.com

**Comment by ishansd94** [comment]
+1

**Comment by cripsins** [comment]
It looks like and API update, instead of using the key from videosources from the coursesOverview query, update the query to include signedUrl and download using that

**Comment by myturf** [comment]
Can you point out the relevant code please ?
