### ISSUE TITLE
Update Extracting Cookies and Usage

### ISSUE THREAD

**Issue by vegazbabz** [r0oth3x49/acloud-dl#65]
Is it possible that you could update the Extracting Cookies and Usage section? Seems like it is not accurate anymore? Or maybe just explain a bit further.
Thanks!
#55

**Comment by r0oth3x49** [comment]
@vegazbabz Unfortunately i don't have currently any account that i could use to prepare a proper guide for that but i 'm mentioning few steps below that might help.

Steps.
 - Login to your acloud account.
 - Launch **Inspect Element** and goto **Network** Tab, In the network tab menu bar click/select on **XHR**.
 - Now Refresh the page. You should see requesting going through your browser in **Network** tab.
 - Find the request similar to.
    ```
    POST /bff/graphql/protected HTTP/1.1
    Host: prod-api.acloud.guru
    User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:63.0) Gecko/20100101 Firefox/63.0
    Accept: application/json, text/plain, */*
    Accept-Language: en-US,en;q=0.5
    Accept-Encoding: gzip, deflate, br
    Referer: https://acloud.guru/
    Authorization: Bearer {ACCESS_TOKEN}
    Content-Type: application/json;charset=utf-8
    Content-Length: 673
    Origin: https://acloud.guru
    DNT: 1
    Connection: keep-alive
    ```
- The request should contain a header called **Authorization: Bearer {A LONG TOKEN}**
- Copy the entire request to a file let say **cookies.txt**.
- Then run the acloud-dl normally as described in **README** file.

**Comment by vegazbabz** [comment]
Thanks, I will try that!
They have free courses right now, so that is the only reason I have an account.

**Comment by vegazbabz** [comment]
It is working like a charm!
Thank you very much, really appreciate it :-)
Just a note for others, you need to install the requirements/modules with Python 3, e.g. if you have both v2 and v3 installed:

**pip3** install -r requirements.txt
