### ISSUE TITLE
Extracting cookies for Google OAuth

### ISSUE THREAD

**Issue by EZarnosky** [r0oth3x49/acloud-dl#66]
I saw the issue #55 & #65 on how to save cookies, however I am having issues getting that to work for my account which uses Google OAuth. Is the process different?

my cookie.txt contains the following (string was editted):

authorization: Bearer sh247adm7aer74lk324h9sasdfu22hasdf3s

**Comment by r0oth3x49** [comment]
you should check the request going to `/graphql`  endpoint that contains the auth token, didn;t tried with google oauth or other yet. but you can share account on this weekend i can take a look at it.

If you can't share please do close the issue also.

**Comment by r0oth3x49** [comment]
6 days no response going to close the issue.
