### ISSUE TITLE
Extracting Cookies 

### ISSUE THREAD

**Issue by hamidnia** [r0oth3x49/acloud-dl#67]
look like learn.acloud.guru changed and extract query from XHR not working as mentioned in the readme.

**Comment by M1haiR** [comment]
works for me if you grab the cookie from any course page, after you clicked "Start the course". The cookie itself should be a long alphanumeric string (1086 characters in my case), on other pages, or from other XHR elements there are much shorter cookies, these will not work.

However, I was not able to use the range functionality besides the simple x+ use case. Don't get how to use it like x-y for instance.

**Comment by r0oth3x49** [comment]
> 
> 
> works for me if you grab the cookie from any course page, after you clicked "Start the course". The cookie itself should be a long alphanumeric string (1086 characters in my case), on other pages, or from other XHR elements there are much shorter cookies, these will not work.
> 
> However, I was not able to use the range functionality besides the simple x+ use case. Don't get how to use it like x-y for instance.

for now the range mean exact how you are using it. should be ==> ***x+***,  The is no implementation for x-y as of yet.

**Comment by r0oth3x49** [comment]
> 
> 
> look like learn.acloud.guru changed and extract query from XHR not working as mentioned in the readme.

it didn't changed anything.
you should be looking for JWT token.
