### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by nag9s** [r0oth3x49/acloud-dl#69]
Getting the following error

OSError: [Errno 22] Invalid argument: '\\\\?\\\\\\?\\C:\\Users\\Administrator\\Downloads\\Compressed\\acloud-dl-master\\acloud-dl-master\\AWS Certified Solutions Architect - Professional 2020\\02 Data Stores\\019 Video Deep Dive Using Hybrid Storage with AWS Storage Gateway to Solve On-Premises Storage Problems.txt'

**Comment by r0oth3x49** [comment]
try to changing the output path.
