### ISSUE TITLE
URLError : either your internet connection is not working or server aborted the request

### ISSUE THREAD

**Issue by felixschilling** [r0oth3x49/acloud-dl#71]
Hi,

I get the following issue when trying to download. I used the latest version.

**Comment by r0oth3x49** [comment]
can't reproduce as i don't have any account, would be great if you can share your creds so that i can try to reproduce and fix.

**Comment by tarunm97** [comment]
i have the account @r0oth3x49 , it is a demo account trial version activate for 7 days, can it will help??
