### ISSUE TITLE
Not downloading Hands on lab video

### ISSUE THREAD

**Issue by rishabh41996** [r0oth3x49/acloud-dl#74]
Hi Team,

Thanks for this amazin project. I jut have one issue. It's not downloading the hands on lab videos that we have in courses. Is there any additional flag that need to be turned on or it is not possible at the moment to download it ?

**Comment by r0oth3x49** [comment]
@rishabh41996 i might need an account to check and try fix it, sorry for the delayed response as i was busy with some office work.
