### ISSUE TITLE
Fails for some videos, possibly due to some character in name

### ISSUE THREAD

**Issue by izeetek** [r0oth3x49/acloud-dl#77]
![image](https://user-images.githubusercontent.com/89616385/131051731-bd058e83-dd1e-4d97-a714-1351e91c3c90.png)

**Comment by harmitstar** [comment]
Video with "**Demo**" keyword and contain  "**[**" character are being skipped and not being downloaded

**Comment by r0oth3x49** [comment]
@izeetek you should enable long path in windows if you are using windows 10. otherwise change the download path to some thing short like: E://tuts//
