### ISSUE TITLE
after merging linuxacademy and cloud guru still working ?

### ISSUE THREAD

**Issue by mariuszzab** [r0oth3x49/acloud-dl#86]

**Comment by r0oth3x49** [comment]
@mariuszzab are you still facing the issue if so, i might need your account creds to reproduce and fix. If that is okay for you then you can send your creds with details of the issue you are facing and the course urls/names would be a plus to track the issue and fix ASAP on that course.

email: `nasir251292@gmail.com`

**Comment by r0oth3x49** [comment]
almost 6 months no response from you will close this issue.
