### ISSUE TITLE
Udemy-dl access token is not recognised

### ISSUE THREAD

**Issue by botK19** [r0oth3x49/acloud-dl#87]
Sorry, i writing here because udemy dl repo is closed...
Udemy-dl access token is not recognised
https://stackoverflow.com/questions/69607496/udemy-dl-access-token-is-not-recognised

[i] : Trying to login using session cookie
[-] : Udemy Says: 403 Forbidden session cookie seems to be expired...
[i] : Updating session cookie..
[i] : Logged in successfully.
[-] : Udemy Says: 403 Forbidden on www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,published_title&page=1&page_size=1000&ordering=-last_accessed,-access_time&search=python-course

I have tried several times to empty cookies in by Mozilla browser, log out and in from Udemy.com and update the actual access_token at token.txt, but the error persists when I go back to python.

What should I do?

**Comment by markkuit** [comment]
See [udemy-dl issue #572](https://github.com/r0oth3x49/udemy-dl/issues/572) and relevant comments; also:

> ### Warning
> 
> **Udemy has started to encrypt many of the course videos, so downloading them may be impossible/illegal because it involves decrypting DRM'd videos which opens up the author to DMCA takedowns/lawsuits.  If you use udemy-dl and some/all videos are skipped, please don't open a new issue or comment that the issue still exists.  All requests to bypass DRM/encryption will be ignored.**
> 
> If you'd like to see the full context, then read [issue 627](https://github.com/r0oth3x49/udemy-dl/issues/627).
