### ISSUE TITLE
Some asset downloads don't work

### ISSUE THREAD

**Issue by ianwinter** [r0oth3x49/acloud-dl#9]
From the `[*] : Course 'Google Certified Associate Cloud Engineer'.`

```
[*] : Downloading asset(s)
[*] : Downloading (003 Lab Script Commands.txt)
[*] : Asset : '003 Lab Script Commands.txt' (download skipped).
[-] : Exception : 'NoneType' object has no attribute 'strip'
```

Also seen the same error for Ansible course and HTML files.

Had a look at the code, but, python is beyond me to know where to debug.

**Comment by r0oth3x49** [comment]
@ianwinter i might need an account to debug & fix which currently i don't have. the reason could be url to this asset was not extracted by acloud-dl but need to investigate.

**Comment by aws25** [comment]
ABC-MacBook-Pro:acloud-dl def$ sudo python acloud-dl.py -c file_containing_cookie.txt
Password:
Traceback (most recent call last):
  File "acloud-dl.py", line 7, in <module>
    import acloud
  File "/Users/def/Desktop/acloud-dl/acloud/__init__.py", line 32, in <module>
    from ._acloud import courses
  File "/Users/def/Desktop/acloud-dl/acloud/_acloud.py", line 26, in <module>
    from ._internal import InternCloudGuruCourse as CloudGuru
  File "/Users/def/Desktop/acloud-dl/acloud/_internal.py", line 30, in <module>
    from ._extract import CloudGuru
  File "/Users/def/Desktop/acloud-dl/acloud/_extract.py", line 45, in <module>
    from ._sanitize import (
  File "/Users/def/Desktop/acloud-dl/acloud/_sanitize.py", line 10, in <module>
    from unidecode import unidecode
ImportError: No module named unidecode

**Comment by r0oth3x49** [comment]
@aws25 you should install the requirements 1st to run the tool

**Comment by nebb00** [comment]
I get this quite often

```
[*] : Downloading asset(s)
[*] : Downloading (xxxxx.html)
[*] : Asset : 'xxxx.html' (download skipped).
[-] : Exception : 'content-length'
```

**Comment by r0oth3x49** [comment]
@nebb00 you can [email me](mailto:nasir251292@gmail.com) your credentials to reproduce & fix the issue, Currently i don't have any account on acloud guru which i can use to fix the issue.
