### ISSUE TITLE
Limited List

### ISSUE THREAD

**Issue by mogbebor-jjtech** [r0oth3x49/acloud-dl#93]
This seems to be a limited list. It only shows about 71 courses and not the updated or latest courses. Is there a way to sort by latest or name or increase the list size to show more than 71 courses?
![Course List](https://user-images.githubusercontent.com/102127835/171032152-f25e9c9a-38a1-4259-a794-c9af3ede5f02.png)

**Comment by c-s-alex** [comment]
I'm having the same issue, only 3 courses show up in my list :(

**Comment by MohiuddinSumon** [comment]
Basically sometime all coerces are not coming , some are missing

**Comment by MohiuddinSumon** [comment]
are you guys using any flag ? what happens if you use -i ?

**Comment by r0oth3x49** [comment]
you guys need to register into the courses first then it will be listed by the tools.

**Comment by MohiuddinSumon** [comment]
for me I was using -n, so if any download stared previously it wasn't showing , removing the flag solved it for me

**Comment by nandy6666** [comment]
> you guys need to register into the courses first then it will be listed by the tools.

Thanks for the tip
