### ISSUE TITLE
unable to find file 'file_containing_cookie.txt'.

### ISSUE THREAD

**Issue by asish6600** [r0oth3x49/acloud-dl#95]
unable to find file 'file_containing_cookie.txt'.

**Comment by EROR4IK** [comment]
'file_containing_cookie.txt' is any txt file with _auth0_token_ cookie. To get this cookie, you need to: 

1. Be logged in
2. Open any course
3. Start this course
4. Inspect the page (right-click on any free space, choose "Inspect")
5. In the opened menu, navigate to "Application"
6. In the "Storage" section go-to cookies, filter out auth0_token
7. Copy the "Value" section of it
8. Create an empty txt file(for simplicity it may be created in the same folder as _acloud-dl.py_)
9. Paste in the file _auth0_token=Value_
10. Save it
11. Profit!

_file_containing_cookie.txt_ example:
`auth0_token=eyJhblRfqijbjbDEYvxZrznFChblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDE`

Hope I could help.

**Comment by Alex-ll-2021** [comment]
> 'file_containing_cookie.txt' is any txt file with _auth0_token_ cookie. To get this cookie, you need to:
> 
> 1. Be logged in
> 2. Open any course
> 3. Start this course
> 4. Inspect the page (right-click on any free space, choose "Inspect")
> 5. In the opened menu, navigate to "Application"
> 6. In the "Storage" section go-to cookies, filter out auth0_token
> 7. Copy the "Value" section of it
> 8. Create an empty txt file(for simplicity it may be created in the same folder as _acloud-dl.py_)
> 9. Paste in the file _auth0_token=Value_
> 10. Save it
> 11. Profit!
> 
> _file_containing_cookie.txt_ example: `auth0_token=eyJhblRfqijbjbDEYvxZrznFChblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDEhblRfqijbjbDE`
> 
> Hope I could help.

Thanks, this is very detailed than Readme

**Comment by r0oth3x49** [comment]
@EROR4IK thanks for explaining it.
