### ISSUE TITLE
Authorization error : it seems your authorization token is expired

### ISSUE THREAD

**Issue by vanhook** [r0oth3x49/acloud-dl#97]
I already put the fresh token (refresh page) but I've got an error:

[*] : Downloading accessible courses information ..
[*] : Course 'TensorFlow Developer Certificate Exam Prep'.
**[*] : Downloading course information .. -[-] : Authorization error : it seems your authorization token is expired.**
[i] : Login again & copy Request headers for a single request to file..

**Comment by baldangombodombo** [comment]
@vanhook I am having the same issue,  how did you solve this issue?
